/* tslint:disable */
/* eslint-disable */
/**
 * OatMilk.Backend.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { CharacterAbilityScoreProficiencyRequest } from './character-ability-score-proficiency-request';
import { CharacterAbilityScoreRequest } from './character-ability-score-request';
import { CharacterAttributeRequest } from './character-attribute-request';
import { CharacterDescriptionRequest } from './character-description-request';

/**
 * 
 * @export
 * @interface CharacterRequest
 */
export interface CharacterRequest {
    /**
     * 
     * @type {string}
     * @memberof CharacterRequest
     */
    name: string;
    /**
     * A list of all attributes. If this is null, character\'s attributes won\'t be updated.
     * @type {Array<CharacterAttributeRequest>}
     * @memberof CharacterRequest
     */
    attributes: Array<CharacterAttributeRequest> | null;
    /**
     * A list of all attributes. If this is null, character\'s ability scores won\'t be updated.
     * @type {Array<CharacterAbilityScoreRequest>}
     * @memberof CharacterRequest
     */
    abilityScores: Array<CharacterAbilityScoreRequest> | null;
    /**
     * A list of all ability score proficiencies. If this is null, character\'s proficiencies won\'t be updated.  All requests here will be parented under existing ability scores.
     * @type {Array<CharacterAbilityScoreProficiencyRequest>}
     * @memberof CharacterRequest
     */
    abilityScoreProficiencies: Array<CharacterAbilityScoreProficiencyRequest> | null;
    /**
     * A list of all attributes. If this is null, character\'s descriptions won\'t be updated.
     * @type {Array<CharacterDescriptionRequest>}
     * @memberof CharacterRequest
     */
    descriptions: Array<CharacterDescriptionRequest> | null;
}


