/* tslint:disable */
/* eslint-disable */
/**
 * OatMilk.Backend.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CharacterAttributeResponse
 */
export interface CharacterAttributeResponse {
    /**
     * 
     * @type {string}
     * @memberof CharacterAttributeResponse
     */
    id?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CharacterAttributeResponse
     */
    name?: string | null;
    /**
     * 
     * @type {number}
     * @memberof CharacterAttributeResponse
     */
    currentValue?: number;
    /**
     * 
     * @type {number}
     * @memberof CharacterAttributeResponse
     */
    defaultValue?: number;
}


