/* tslint:disable */
/* eslint-disable */
/**
 * OatMilk.Backend.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CharacterDescriptionRequest
 */
export interface CharacterDescriptionRequest {
    /**
     * 
     * @type {string}
     * @memberof CharacterDescriptionRequest
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof CharacterDescriptionRequest
     */
    name: string | null;
    /**
     * 
     * @type {string}
     * @memberof CharacterDescriptionRequest
     */
    value: string | null;
}


