/* tslint:disable */
/* eslint-disable */
/**
 * OatMilk.Backend.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { CharacterAbilityScoreResponse } from './character-ability-score-response';
import { CharacterAttributeResponse } from './character-attribute-response';
import { CharacterDescriptionResponse } from './character-description-response';
import { CharacterLevelResponse } from './character-level-response';

/**
 * 
 * @export
 * @interface CharacterResponse
 */
export interface CharacterResponse {
    /**
     * 
     * @type {string}
     * @memberof CharacterResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof CharacterResponse
     */
    identifier: string;
    /**
     * 
     * @type {string}
     * @memberof CharacterResponse
     */
    createdDateTimeUtc?: string;
    /**
     * 
     * @type {string}
     * @memberof CharacterResponse
     */
    updatedDateTimeUtc?: string;
    /**
     * 
     * @type {string}
     * @memberof CharacterResponse
     */
    name: string;
    /**
     * 
     * @type {CharacterLevelResponse}
     * @memberof CharacterResponse
     */
    level: CharacterLevelResponse;
    /**
     * 
     * @type {Array<CharacterAttributeResponse>}
     * @memberof CharacterResponse
     */
    attributes: Array<CharacterAttributeResponse>;
    /**
     * 
     * @type {Array<CharacterAbilityScoreResponse>}
     * @memberof CharacterResponse
     */
    abilityScores: Array<CharacterAbilityScoreResponse>;
    /**
     * 
     * @type {Array<CharacterDescriptionResponse>}
     * @memberof CharacterResponse
     */
    descriptions: Array<CharacterDescriptionResponse>;
}


