/* tslint:disable */
/* eslint-disable */
/**
 * OatMilk.Backend.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CharacterAbilityScoreRequest
 */
export interface CharacterAbilityScoreRequest {
    /**
     * 
     * @type {string}
     * @memberof CharacterAbilityScoreRequest
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof CharacterAbilityScoreRequest
     */
    name?: string | null;
    /**
     * 
     * @type {number}
     * @memberof CharacterAbilityScoreRequest
     */
    value?: number;
    /**
     * 
     * @type {boolean}
     * @memberof CharacterAbilityScoreRequest
     */
    proficient?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof CharacterAbilityScoreRequest
     */
    expertise?: boolean;
}


