/* tslint:disable */
/* eslint-disable */
/**
 * OatMilk.Backend.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { CharacterAbilityScoreProficiencyRequest } from './character-ability-score-proficiency-request';
import { CharacterAbilityScoreRequest } from './character-ability-score-request';
import { CharacterAttributeRequest } from './character-attribute-request';
import { CharacterDescriptionRequest } from './character-description-request';

/**
 * 
 * @export
 * @interface CharacterRequest
 */
export interface CharacterRequest {
    /**
     * 
     * @type {string}
     * @memberof CharacterRequest
     */
    name: string;
    /**
     * 
     * @type {Array<CharacterAttributeRequest>}
     * @memberof CharacterRequest
     */
    attributes?: Array<CharacterAttributeRequest> | null;
    /**
     * 
     * @type {Array<CharacterAbilityScoreRequest>}
     * @memberof CharacterRequest
     */
    abilityScores?: Array<CharacterAbilityScoreRequest> | null;
    /**
     * 
     * @type {Array<CharacterAbilityScoreProficiencyRequest>}
     * @memberof CharacterRequest
     */
    abilityScoreProficiencies?: Array<CharacterAbilityScoreProficiencyRequest> | null;
    /**
     * 
     * @type {Array<CharacterDescriptionRequest>}
     * @memberof CharacterRequest
     */
    descriptions?: Array<CharacterDescriptionRequest> | null;
}


