/* tslint:disable */
/* eslint-disable */
/**
 * OatMilk.Backend.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * User DTO.  Passed as a response when a user\'s details are requested.
 * @export
 * @interface UserResponse
 */
export interface UserResponse {
    /**
     * 
     * @type {string}
     * @memberof UserResponse
     */
    id: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserResponse
     */
    displayName: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserResponse
     */
    email: string | null;
}


