/* tslint:disable */
/* eslint-disable */
/**
 * OatMilk.Backend.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { CharacterSummaryResponsePageResponse } from '../models';
// @ts-ignore
import { ErrorResponse } from '../models';
/**
 * CharacterSummaryApi - axios parameter creator
 * @export
 */
export const CharacterSummaryApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} [searchByName] 
         * @param {string} [sortColumnName] Name of the column to sort by.
         * @param {boolean} [sortAscending] Whether or not to sort in ascending order.
         * @param {number} [pageIndex] 
         * @param {number} [pageSize] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        characterSummaryGet: async (searchByName?: string, sortColumnName?: string, sortAscending?: boolean, pageIndex?: number, pageSize?: number, options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/Character/summary`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (searchByName !== undefined) {
                localVarQueryParameter['SearchByName'] = searchByName;
            }

            if (sortColumnName !== undefined) {
                localVarQueryParameter['SortColumnName'] = sortColumnName;
            }

            if (sortAscending !== undefined) {
                localVarQueryParameter['SortAscending'] = sortAscending;
            }

            if (pageIndex !== undefined) {
                localVarQueryParameter['PageIndex'] = pageIndex;
            }

            if (pageSize !== undefined) {
                localVarQueryParameter['PageSize'] = pageSize;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * CharacterSummaryApi - functional programming interface
 * @export
 */
export const CharacterSummaryApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = CharacterSummaryApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} [searchByName] 
         * @param {string} [sortColumnName] Name of the column to sort by.
         * @param {boolean} [sortAscending] Whether or not to sort in ascending order.
         * @param {number} [pageIndex] 
         * @param {number} [pageSize] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async characterSummaryGet(searchByName?: string, sortColumnName?: string, sortAscending?: boolean, pageIndex?: number, pageSize?: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CharacterSummaryResponsePageResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.characterSummaryGet(searchByName, sortColumnName, sortAscending, pageIndex, pageSize, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * CharacterSummaryApi - factory interface
 * @export
 */
export const CharacterSummaryApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = CharacterSummaryApiFp(configuration)
    return {
        /**
         * 
         * @param {string} [searchByName] 
         * @param {string} [sortColumnName] Name of the column to sort by.
         * @param {boolean} [sortAscending] Whether or not to sort in ascending order.
         * @param {number} [pageIndex] 
         * @param {number} [pageSize] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        characterSummaryGet(searchByName?: string, sortColumnName?: string, sortAscending?: boolean, pageIndex?: number, pageSize?: number, options?: any): AxiosPromise<CharacterSummaryResponsePageResponse> {
            return localVarFp.characterSummaryGet(searchByName, sortColumnName, sortAscending, pageIndex, pageSize, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * CharacterSummaryApi - object-oriented interface
 * @export
 * @class CharacterSummaryApi
 * @extends {BaseAPI}
 */
export class CharacterSummaryApi extends BaseAPI {
    /**
     * 
     * @param {string} [searchByName] 
     * @param {string} [sortColumnName] Name of the column to sort by.
     * @param {boolean} [sortAscending] Whether or not to sort in ascending order.
     * @param {number} [pageIndex] 
     * @param {number} [pageSize] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CharacterSummaryApi
     */
    public characterSummaryGet(searchByName?: string, sortColumnName?: string, sortAscending?: boolean, pageIndex?: number, pageSize?: number, options?: any) {
        return CharacterSummaryApiFp(this.configuration).characterSummaryGet(searchByName, sortColumnName, sortAscending, pageIndex, pageSize, options).then((request) => request(this.axios, this.basePath));
    }
}
