name: Azure Container Instances CI/CD
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
        - run: |
            docker build -f ./OatMilk.Backend.Api/Dockerfile . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/oat-milk-backend:${{ github.sha }} -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/oat-milk-backend:main
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/oat-milk-backend --all-tags
