on: [push]
name: Linux_Container_Workflow

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
          
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        
        - name: 'Build and push image'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        - run: |
            docker build -f ./OatMilk.Backend.Api/Dockerfile . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/oat-milk-backend:prod
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/oat-milk-backend:prod

        - name: 'Deploy to Azure Container Instances'
          uses: 'azure/aci-deploy@v1'
          with:
            resource-group: ${{ secrets.RESOURCE_GROUP }}
            dns-name-label: oat-milk-backend
            image: ${{ secrets.REGISTRY_LOGIN_SERVER }}/oat-milk-backend:prod
            registry-login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            registry-username: ${{ secrets.REGISTRY_USERNAME }}
            registry-password: ${{ secrets.REGISTRY_PASSWORD }}
            name: oat-milk-backend
            secure-environment-variables: ConnectionStrings__MainDatabase="${{ secrets.MAIN_DATABASE_CONNECTION_STRING }}" Auth__UserTokenSecret="${{ secrets.USER_TOKEN_SECRET_AUTH }}"
            location: 'australiaeast'
