name: Azure Container Instances CI/CD
on:
  push:
    branches:
      - main

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        - name: 'Checkout Code from Repository' 
          uses: actions/checkout@v2
        - name: 'Set up .NET 5.0.x'
          uses: actions/setup-dotnet@v1
          with:
            dotnet-version: '5.0.x'
        - name: 'Publish a Release of the App'
          run: |
            cd OatMilk.Backend.Api/
            dotnet publish -c Release --output '../published-app'
        - name: 'Deploy to Azure App Service'
          uses: azure/webapps-deploy@v2
          with:
            app-name: 'oat-milk-backend'
            publish-profile: ${{ secrets.PUBLISH_PROFILE }}
            package: ./published-app
