name: Publish Typescript Axios Sdk

on:
  push:
    branches: [ main ]

  workflow_dispatch:

env:
  ARTIFACT_PATH: ./artifact 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
          
      - name: openapi-generator-generate-action
        uses: craicoverflow/openapi-generator-generate-action@v1.0.0
        with:
          generator: typescript-axios
          input: OatMilk.Backend.Api/openapi.json
          output: ${{env.ARTIFACT_PATH}}
      
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: .code
          path: ${{env.ARTIFACT_PATH}}
