name: Publish Typescript Axios Sdk

on:
  push:
    branches: [ main ]

  workflow_dispatch:

env:
  WORKING_DIRECTORY: OatMilk.Backend.Api/Sdks/TypescriptAxios

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
      
      - name: npm install
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: npm install
      
      - name: npm publish
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
