name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Build - dotnet build
      run: dotnet build ./OatMilk.Backend.Api/OatMilk.Backend.Api.csproj --configuration Release
    - name: Publish - dotnet publish
      run: dotnet publish ./OatMilk.Backend.Api/OatMilk.Backend.Api.csproj -c Release -o ./artifact
    - name: Test - dotnet test
      run: dotnet test --no-build --verbosity normal
    - name: Publish Artifact
      uses: actions/upload-artifact@v2
      with:
        name: .net-app
        path: ./artifact
