name: Publish Typescript Axios Sdk

on:
  push:
    branches: [ main ]

  workflow_dispatch:

env:
  WORKING_DIRECTORY: OatMilk.Backend.Api/Sdks/TypescriptAxios

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: npm install
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: npm install
      
      - name: npm publish
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
