name: Publish Typescript Axios Sdk

on:
  push:
    branches: [ main ]

  workflow_dispatch:

env:
  ARTIFACT_PATH: ./artifact 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: change to API directory
        run: cd OatMilk.Backend.Api/
          
      - name: openapi-generator-generate-action
        run: npx @openapitools/openapi-generator-cli generate
      
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: .code
          path: ${{env.ARTIFACT_PATH}}
