name: Publish Typescript Axios Sdk

on:
  push:
    branches: [ main ]

  workflow_dispatch:

env:
  ARTIFACT_PATH: ./artifact 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: cd to typescript axios sdk
        run: cd OatMilk.Backend.Api/Sdks/TypescriptAxios
      
      - name: npm install
        run: npm install
      
      - name: npm publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
