# This is a basic workflow to help you get started with Actions

name: Publish Typescript Axios Sdk

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  ARTIFACT_PATH: ./artifact 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: openapi-generator-generate-action
        # You may pin to the exact commit or the version.
        # uses: craicoverflow/openapi-generator-generate-action@b9c2152934cd8ea4938eb2d8a3de7905b9086285
        uses: craicoverflow/openapi-generator-generate-action@v1.0.0
        with:
          # The name of the generator to use
          generator: typescript-axios
          # OpenAPI specification file to use as the source for generation
          input: ./OatMilk.Backend.Api/openapitools.json
          # The output directory of the generated code
          output: ${{env.ARTIFACT_PATH}}
          
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: .code
          path: ${{env.ARTIFACT_PATH}}
